addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.3.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.0.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.7.5")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"             % "0.10.0")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                % "5.6.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"                 % "1.4.6")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"            % "1.5.5")
